apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-config
  namespace: aurora-prod
data:
  APP_NAME: "fraud"
  SERVER_PORT: "8081"
  DB_URL: "jdbc:postgresql://postgres.aurora-prod.svc.cluster.local:5432/fraud"
  DB_USERNAME: "admin"
  DB_PASSWORD: "admin"
  RABBITMQ_ADDR: "amqp://rabbitmq.aurora-prod.svc.cluster.local:5672"
  LOG_LEVEL: "INFO"
